### PR TITLE
Replace --testnet flag with --network and change config accordingly

### PR DESCRIPTION
**Pull request by etimoz**
Lighthouse `v1.0.0` replaces `--testnet` with `--network`. Made flag and config changes. Set network default to mainnet. PR https://github.com/sigp/lighthouse-docker/pull/39 can be closed if this gets merged.

### CODE REVIEW

**Review by jburnett — APPROVED** [review]
I was going to propose these changes, but etimoz's are better. I had forgotten about default.env, so I'd prefer these over mine.  HTH

**Comment by lama70** [comment]
It's for today? Thank you

**Review by AgeManning — APPROVED** [review]
This looks good. Thanks for the update. 

Sorry for the delay

**Comment by lama70** [comment]
Thank you!!!

**Pull request merged**
