### PR TITLE
Add net API to geth, add script to wait for geth

### PR DESCRIPTION
**Pull request by yorickdowne**
This addresses #28 as well as #29.

I've pulled in https://github.com/vishnubob/wait-for-it as a git submodule, then manually copied that script to scripts/

This may not be your desired way of doing things. Consider this PR a suggestion, only.

### CODE REVIEW

**Comment by kvbik** [comment]
I am little bit worried the script `wait-for-it` would have a hard time, since there is no `nc` in the `lighthouse` containers! But haven't tried your PR in action yet.

**Comment by kvbik** [comment]
Another idea - wouldn't just plain `docker-compose`'s `depends_on` do the trick? I understand it does not wait for the other app (in the other docker) to be ready, but maybe the couple of mili-seconds would be enough?

**Comment by yorickdowne** [comment]
Depends-on won't work. I've now solved this another way in my own docker-compose effort. I'm using dockerize and a small script to parse the URL and then check for tcp:// connectivity. This has the advantage that it works with things like infura, the disadvantage that dockerize needs to be in the container.

docker and docker-compose really don't solve this well.

Here's yet another idea: You can solve it in beacon. prysm for example doesn't exit when it can't find its eth1 endpoint, it just keeps looking for it, the way the validator looks for the beacon. You could change the beacon code so it'll loop until someone puts it out of its misery or it can establish a connection

**Review by AgeManning — CHANGES_REQUESTED** [review]
Thanks for this! 

This seems to be a bug that has recently been introduced into the beacon node. The beacon node should continuously try to connect to the eth1 endpoint and not terminate. 

We will fix this. 

This means we don't need the `wait-for-it` logic. However we do still need the `net` API. Could you adjust this PR to just add the `net` API, and we'll update the beacon node to resolve the race condition. 

:)

**Comment by kvbik** [comment]
Awesome @AgeManning thx for clarification! And making the beacon work like this ;) great not to depend on `wait4it`. As this PR introduces big changes, maybe let's just close it and create a small one with the two fixed options for `geth`: `--http.api "eth,net"` and `--nousb` (this one just removes annoying warning message). Kudos to @yorickdowne for making it work!!!

**Comment by yorickdowne** [comment]
Changed this PR to just make those two changes, API and --nousb

**Review by AgeManning — APPROVED** [review]

**Pull request merged**
