### PR TITLE
Adopted all path to user lighthouse instead of root

### LINKED ISSUE #17: Docker user changed
The newest docker image uses the user `lighthouse` instead of `root`, which results in a `Permission denied` error when starting the validator and beacon node

```
beacon_node_1       | sh: 0: Can't open /root/scripts/start-beacon-node.sh
lighthouse-docker_beacon_node_1 exited with code 127
```

### PR DESCRIPTION
**Pull request by eiabea**
Fixes #17 

Some pitfalls which may need to be addressed with a good documentation or a `entrypoint.sh`

- The already existing data needs to be `chown` to the new `lighthouse` user (uid: 999)
- The `validator_definitions.yml` needs to be edited to use the new paths

### CODE REVIEW

**Comment by ErikBjare** [comment]
I applied the patch, ran `sudo chown -R 999 lighthouse-data/ network/`, then edited `validator_definitions.yml`.

Seems to work, but I keep getting `WARN Could not write metadata to disk        error: Permission denied (os error 13), file: "/root/network""metadata", service: libp2p`. Where does it get the `/root/network` path from?

**Comment by eiabea** [comment]
> I applied the patch, ran `sudo chown -R 999 lighthouse-data/ network/`, then edited `validator_definitions.yml`.
> 
> Seems to work, but I get warnings like:
> 
> ```
> WARN Could not write node key to file: "/root/network/key". error: Permission denied (os error 13), service: libp2p`
> WARN Could not write ENR to file             error: Permission denied (os error 13), file: "/root/network""enr.dat", service: libp2p
> WARN Could not write metadata to disk        error: Permission denied (os error 13), file: "/root/network""metadata", service: libp2p
> ```
> 
> Where does it get the `/root/network` path from?

The `./network` is bound in the volumes section:

```
 volumes:
            - ./data/lighthouse:/home/lighthouse/.lighthouse
            - ./scripts:/home/lighthouse/scripts
            - ./network:/root/network // <-- here
```

I am still not sure why this volume is bound, i had no issues with this volume

**Comment by ErikBjare** [comment]
@eiabea See my edit. I'd already edited the volumes section, that was not the issue.

**Comment by eiabea** [comment]
@ErikBjare what is the purpose of persisting the `network` directory?

My implementation just does not mount the `network` directory, but if this is necessary i will look into a fix

**Comment by ErikBjare** [comment]
@eiabea I don't know, but I assume whoever added the mount and CLI flag had a good reason.

**Comment by AgeManning** [comment]
The network directory was mounted separately for some of our internal testnets. It stores the ENR of the node. So we this way we can access it easily for bootnodes and connect to other nodes automatically.

**Review by AgeManning — APPROVED** [review]
Looks good to me

**Comment by paulhauner** [comment]
> @ErikBjare what is the purpose of persisting the `network` directory?
> 
> My implementation just does not mount the `network` directory, but if this is necessary i will look into a fix

Among other things, the network directory contains the p2p network identity of the node and it's ideal to persist it.

By default (i.e., without [this flag](https://github.com/sigp/lighthouse-docker/blob/5f671d1fce875b815117f08df35f9fd0687cfa6d/scripts/start-beacon-node.sh#L22)) the network directory is in `~/.lighthouse/network`, however we have made it external here since that was helpful for testnets. It's not so helpful anymore.

@eiabea i would suggest dropping the `--network-dir` flag which would retain persistence via the `.lighthouse/network` directory and avoid needing to persist another volume.

**Comment by paulhauner** [comment]
> @eiabea i would suggest dropping the --network-dir flag which would retain persistence via the .lighthouse/network directory and avoid needing to persist another volume.

I'm also happy for this to proceed without this change :)

**Pull request merged**
